from typing import Literal

PARQUET_COMPRESSION: Literal['zstd'] = 'zstd'
PARQUET_COMPRESSION_LEVEL = 3
STREAM_BATCH_SIZE = 200_000
MEMORY_SPLIT_RECORD_THRESHOLD = 10_000
CHUNK_RECORD_COUNT = 25_000
APPEND_TEMP_SUFFIX = '.parquet.tmp'
